axelor/open-suite-webapp

src/main/resources/application.properties
src/main/webapp/css/theme-default/theme.css

in wizard-supplier-view and wizard-supplier-client

#5348 Added css class to display icons correctly 

---

src/main/resources/application.properties

Add configurations for encrypted fields and Quartz scheduler.

---

src/main/resources/application.properties

Fix context.appLogo

---

changelogs/README.md
changelogs/unreleased/fix-dark-theme.yml
src/main/webapp/css/modern-dark/theme.css

* Fix focused item in suggest box
* Fix country list background in Phone widget

Dark theme: fix focused item in suggestbox and phone country list

---

build.gradle
changelogs/unreleased/update-aop-correction-version.yml

Update AOP to 5.4.19

---

settings.gradle

Update AOP to 6.1.4

---

changelogs/unreleased/update-aop.yml
settings.gradle

Update to AOP 7.0.3

---

changelogs/unreleased/update-aop-76535.yml
settings.gradle

Update to AOP 7.0.4

---

settings.gradle

Upgrade to AOP 7.1-SNAPSHOT

---

settings.gradle

Fixed AOP version to 7.1.0

---

buildSrc/src/main/java/com/axelor/gradle/tasks/changelog/ModuleName.java

Add intervention in module list for changelog generation

---

changelogs/unreleased/update-aop-81205.yml
settings.gradle

Update AOP to 7.1.2

---

changelogs/unreleased/update-aop-82156.yml
settings.gradle

Update AOP to 7.1.4

---

changelogs/unreleased/update-aop-84780.yml
settings.gradle

Update Axelor Open Platform to 7.1.5

---

changelogs/unreleased/update-aop-85139.yml
settings.gradle

Update Axelor Open Platform to 7.1.7

---

changelogs/unreleased/86513-update-aop-dependency.yml
settings.gradle

Update Axelor Open Platform dependency to 7.1.8

---

changelogs/unreleased/86796-update-aop-dependency.yml
settings.gradle

Update Axelor Open Platform dependency to 7.2.2

---

settings.gradle

Update Axelor Open Platform to 7.2.4

---

changelogs/unreleased/89535-update-aop.yml
settings.gradle

Update Axelor Open Platform to 7.2.5

---

changelogs/unreleased/90650-update-aop.yml
settings.gradle

Update Axelor Open Platform to 7.2.6

---

settings.gradle

update to AOP 7.3.1

---

changelogs/unreleased/92248-update-aop.yml
settings.gradle

Update Axelor Open Platform to 7.3.3

---

changelogs/unreleased/92976-update-aop.yml
settings.gradle

Update AOP to 7.3.4

---

changelogs/unreleased/94264-update-aop.yml
settings.gradle

Update Axelor Open Platform to 7.3.6

---

settings.gradle

Update Axelor Open Platform to 7.4
